module.exports  = {
  days:[
      [ '知乎',
        'zhihu.com',
        '装逼利器，撕逼大战，实时新闻' ],
      [ 'V2EX',
        'v2ex.com',
        '日常搞基' ],
      [ 'Quora',
        'quora.com',
        '这TM抄袭知乎？' ],
      [ 'Stackoverflow',
        'stackoverflow.com',
        'Get what you want' ],
      [ 'segmentfault',
        'segmentfault.com',
        '挺有爱的哈' ],
      [ 'Github',
        'github.com',
        '全球最大同行社交网站' ],
    ],
  edits:[
      [ 'JS Bin',
        'jsbin.com',
        'Online editor' ],
      [ 'JS fiddle',
        'jsfiddle.net',
        '同上' ],
      [ 'CodePen',
        'codepen.io',
        '变着花样玩前端' ],
      [ 'RunJS',
        'runjs.cn',
        '啊，国内的'],
    ],
  navs:[
      [ 'AnywhereAnything',
        'lackar.com/aa/' ],
      [ 'F2E',
        'f2e.im/static/pages/nav/index.html' ],
      [ '前端导航',
        'w3cmark.com/mark/' ],
      [ '牛大拿',
        'niudana.com/' ],
      [ '安全导航',
        'navisec.it/' ]
  ]
}
