module.exports = {
  days: [
    ['知乎',
      'zhihu.com',
      '装逼利器，撕逼大战，实时新闻'
    ],
    ['V2EX',
      'v2ex.com',
      '日常搞基'
    ],
    ['Quora',
      'quora.com',
      '这TM抄袭知乎？'
    ],
    ['Stackoverflow',
      'stackoverflow.com',
      'Get what you want'
    ],
    ['segmentfault',
      'segmentfault.com',
      '挺有爱的哈'
    ],
    ['Github',
      'github.com',
      '全球最大同行社交网站'
    ],
    ['MDN',
      'https://developer.mozilla.org/zh-CN/'
    ],
  ],
  blogs: [
    ['掘金',
      'http://gold.xitu.io/#/',
      '看看'
    ],
    ['CSS-trike',
      'https://css-tricks.com/'
    ],
    ['Smashing',
      'https://www.smashingmagazine.com/'
    ],
    ['html5Rock',
      'http://www.html5rocks.com/en/'
    ],
    ['infoq',
      'http://www.infoq.com/cn/'
    ],
    ['CSDN',
      'http://www.csdn.net/'
    ],
  ],
  edits: [
    ['JS Bin',
      'jsbin.com',
      'Online editor'
    ],
    ['JS fiddle',
      'jsfiddle.net',
      '同上'
    ],
    ['CodePen',
      'codepen.io',
      '变着花样玩前端'
    ],
    ['RunJS',
      'runjs.cn',
      '啊，国内的'
    ],
  ],
  navs: [
    ['AnywhereAnything',
      'lackar.com/aa/'
    ],
    ['F2E',
      'f2e.im/static/pages/nav/index.html'
    ],
    ['前端导航',
      'w3cmark.com/mark/'
    ],
    ['牛大拿',
      'niudana.com/'
    ],
    ['安全导航',
      'navisec.it/'
    ]
  ],
  doc: [
    ['Medium',
      'https://medium.com/'
    ],
    ['看云',
      'kancloud.cn/explore',
      '大量有用文档'
    ],
    ['GitBook',
      'gitbook.com/explore',
      '2333333333'
    ],
    ['知笔墨',
      'zhibimo.com/explore/books',
      '快死了，续命'
    ],
    ['Open source',
      'http://www.open-open.com/',
      '开源文档库'
    ]
  ],
  community: [
    ['DIV.io',
      'http://div.io/#/welcome'
    ],
    ['Vue',
      'http://forum.vuejs.org/'
    ],
    ['Nodejs',
      'https://cnodejs.org/',
      'Nodejs可以看着'
    ],
    ['W3Cfun',
      'http://www.w3cfuns.com/'
    ],
    ['开源中国',
      'http://www.oschina.net/'
    ],
    ['PHPhub',
      'https://phphub.org/',
      '世界是最好的语言'
    ],
    ['Ionichina',
      'http://ionichina.com/'
    ],
  ],
  regexp:[
    ['入门与语法',
      'http://deerchao.net/tutorials/regex/regex.htm'
    ],
    ['MDN语法与简介',
      'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions?redirectlocale=en-US&redirectslug=JavaScript%2FGuide%2FRegular_Expressions'
    ],
    ['实践',
      'http://regexone.com/'
    ],
    ['正则验证',
      'https://mengzhuo.org/regex/'
    ],
    ['正则练习',
      'http://regex.alf.nu/'
    ],
    ['从简到难',
      'https://regexcrossword.com/'
    ],
    ['正则挑战',
      'http://callumacrae.github.io/regex-tuesday/'
    ],
    ['正则常用表达式',
      'http://www.jb51.net/tools/regex.htm'
    ]
  ]
}